/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models3d/bee_new.glb --transform 
Files: public/models3d/bee_new.glb [16.63MB] > C:\Users\Miraj\Desktop\portfolio3d\bee_new-transformed.glb [1.87MB] (89%)
Author: etro313 (https://sketchfab.com/etro313)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bee-c80f9c2110c847db9375c548f14a0315
Title: Bee
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/bee_new-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_0} skeleton={nodes.Object_116.skeleton} scale={0.001} />
      </group>
    </group>
  )
}

useGLTF.preload('/bee_new-transformed.glb')
