/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models3d/face.glb --transform 
Files: public/models3d/face.glb [94.12MB] > C:\Users\Miraj\Desktop\portfolio3d\face-transformed.glb [92.93MB] (1%)
Author: SonicVisual (https://sketchfab.com/sonicvisual)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/notorius-face-abstract-geometry-animation-loop-89beabda907f402b93e4432b9628d4d7
Title: Notorius Face Abstract Geometry Animation Loop
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/face-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.eyes} position={[0.548, 0.138, 0.208]} rotation={[Math.PI / 2, 0, -0.624]} scale={0.17} />
        <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={materials.mesh_1} morphTargetDictionary={nodes.mesh_1.morphTargetDictionary} morphTargetInfluences={nodes.mesh_1.morphTargetInfluences} rotation={[0, 0.624, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/face-transformed.glb')
