/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models3d/globe.glb --transform 
Files: public/models3d/globe.glb [8.27MB] > C:\Users\Miraj\Desktop\portfolio3d\globe-transformed.glb [722.14KB] (91%)
Author: Vinny Passmore (https://sketchfab.com/HPrendering)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/globe-globechallenge-cf359930f8604a04b194b0f7de74f77b
Title: Globe #GlobeChallenge
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/globe-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" position={[0, -0.035, 0]}>
          <group name="pCylinder9000" scale={100}>
            <mesh name="pCylinder9000_Material003_0" geometry={nodes.pCylinder9000_Material003_0.geometry} material={materials['Material.003']} />
          </group>
          <group name="Globe" scale={100}>
            <mesh name="Globe_Material002_0" geometry={nodes.Globe_Material002_0.geometry} material={materials['Material.002']} />
          </group>
        </group>
        <mesh name="pCylinder9001_Material001_0" geometry={nodes.pCylinder9001_Material001_0.geometry} material={materials['Material.001']} position={[0, -0.035, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/globe-transformed.glb')
